site_name: PFS Target Uploader User Guide
site_url: https://pfs-etc.naoj.hawaii.edu/uploader/doc/
site_author: 'Masato Onodera'


copyright: Copyright &copy; <a href="https://subarutelescope.org">Subaru Telescope</a>, <a href="https://www.nao.ac.jp">NAOJ</a>

# repo_url: https://github.com/Subaru-PFS/spt_target_uploader
# repo_name: PFS Target Uploader

nav:
  - 'Home': index.md
  - 'Inputs': inputs.md
  - 'Validation': validation.md
  - 'Pointing Simulation': PPP.md
  - 'Submission': submission.md
  - 'CLI tool': cli.md
  - 'FAQ & Known Issues': issues.md
  - 'For Developer': developer.md
  - 'About Us': about.md

use_directory_urls: false

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      video_muted: False
  # - social


theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: teal
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  font:
    text: Lato
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/Subaru-PFS/spt_target_uploader
#       name: PFS Target Uploader on GitHub

extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
