site_name: PFS Target Uploader User Guide
site_url: https://pfs-etc.naoj.hawaii.edu/uploader/doc/
site_author: 'Masato Onodera'

nav:
  - 'Home': index.md
  - 'Inputs': inputs.md
  - 'Validation': validation.md
  - 'Time Estimate': PPP.md
  - 'Submission': submission.md
  - 'FAQ & Known Issues': issues.md
  - 'Contact': contact.md

use_directory_urls: false

plugins:
  - search


theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: teal
  icon:
    logo: material/library
  font:
    text: Lato
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select


markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg



# extra_css:
#   - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
