name: Build and deploy documentation for production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod-docs:
    runs-on: [self-hosted, pfs-etc]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run commands
        run: |
          pyenv local 3.11.9
          python3 -m venv .venv
          source .venv/bin/activate
          cd docs
          python3 -m pip install -U mkdocs "mkdocs-material[imaging]" mkdocs-video pymdown-extensions
          mkdocs build --site-dir ${{ vars.DOC_PATH_PROD }}
